apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "helm-chart.fullname" . }}
  labels:
    app: {{ template "helm-chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "helm-chart.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.service.internalPort }}
          {{- if .Values.development }}
          volumeMounts:
            - mountPath: /usr/src/apps/foobar
              name: host-source
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.development }}
      volumes:
        - name: host-source
          hostPath:
            path: {{ .Values.development_path }}
    {{- end }}
